<template>
  <q-page class="q-pa-md bg-dark-neon text-white">
    <div class="page-wrap">
      <div class="row items-center justify-between q-mb-lg"><div><div class="text-h5 text-weight-bold">Estadísticas</div><div class="text-caption text-slate-400">Indicadores calculados a partir de ventas, compras e inventario reales.</div></div><q-btn color="cyan-7" icon="refresh" label="Actualizar" :loading="loading" @click="cargar"/></div>
      <div class="row q-col-gutter-md q-mb-lg">
        <div v-for="m in metricas" :key="m.label" class="col-12 col-sm-6 col-md-3"><q-card class="panel-card" flat><q-card-section><div class="text-caption text-slate-400">{{m.label}}</div><div class="text-h5 text-weight-bold q-mt-sm" :class="m.class">{{m.value}}</div></q-card-section></q-card></div>
      </div>
      <div class="row q-col-gutter-md">
        <div class="col-12 col-lg-8"><q-card class="panel-card" flat><q-card-section><div class="text-h6">Ventas vs compras por mes</div></q-card-section><q-separator dark/><q-card-section><div v-for="mes in series" :key="mes.mes" class="q-mb-lg"><div class="row justify-between text-caption q-mb-xs"><span>{{mes.etiqueta}}</span><span>Ventas Bs {{money(mes.ventas)}} · Compras Bs {{money(mes.compras)}}</span></div><div class="bar"><div class="fill sales" :style="{width:width(mes.ventas)}"></div></div><div class="bar q-mt-xs"><div class="fill purchases" :style="{width:width(mes.compras)}"></div></div></div></q-card-section></q-card></div>
        <div class="col-12 col-lg-4"><q-card class="panel-card" flat><q-card-section><div class="text-h6">Productos más vendidos</div></q-card-section><q-separator dark/><q-list dark separator><q-item v-for="(p,i) in top" :key="p.id"><q-item-section avatar><q-avatar color="cyan-10" text-color="cyan-2">{{i+1}}</q-avatar></q-item-section><q-item-section><q-item-label>{{p.Nombre}}</q-item-label><q-item-label caption class="text-slate-400">{{p.unidades}} unidades vendidas</q-item-label></q-item-section></q-item><q-item v-if="!top.length"><q-item-section class="text-slate-400">Sin ventas registradas.</q-item-section></q-item></q-list></q-card></div>
      </div>
    </div>
  </q-page>
</template>
<script setup>
import {computed,onMounted,ref} from 'vue';import {api} from '../boot/axios';import {useQuasar} from 'quasar';const $q=useQuasar();const loading=ref(false);const d=ref({totales:{},series_mensuales:[],top_productos:[]});const money=v=>Number(v||0).toLocaleString('es-BO',{minimumFractionDigits:2,maximumFractionDigits:2});const series=computed(()=>d.value.series_mensuales||[]);const top=computed(()=>d.value.top_productos||[]);const max=computed(()=>Math.max(1,...series.value.flatMap(x=>[+x.ventas||0,+x.compras||0])));const width=v=>`${Math.max(2,(Number(v||0)/max.value)*100)}%`;const metricas=computed(()=>{const t=d.value.totales||{};return[{label:'Ventas acumuladas',value:`Bs ${money(t.ventas_total)}`,class:'text-green-4'},{label:'Compras acumuladas',value:`Bs ${money(t.compras_total)}`,class:'text-purple-3'},{label:'Valor de inventario',value:`Bs ${money(t.valor_inventario)}`,class:'text-cyan-3'},{label:'Stock bajo',value:`${t.stock_bajo||0} productos`,class:'text-amber-4'}]});const cargar=async()=>{loading.value=true;try{const r=await api.get('/dashboard/totales');d.value=r.data}catch(e){console.error(e);$q.notify({type:'negative',message:'No se pudieron cargar las estadísticas.'})}finally{loading.value=false}};onMounted(cargar)
</script>
<style scoped>.bg-dark-neon{background:#07111f;min-height:100vh}.page-wrap{max-width:1320px;margin:0 auto}.panel-card{background:#111d2e;border:1px solid #26364a;color:white}.text-slate-400{color:#94a3b8}.bar{height:10px;border-radius:8px;background:#253349;overflow:hidden}.fill{height:100%;border-radius:8px}.sales{background:linear-gradient(90deg,#14b8a6,#22d3ee)}.purchases{background:linear-gradient(90deg,#8b5cf6,#ec4899)}</style>
