<template>
  <q-page padding>
    <div class="row items-center justify-between q-mb-lg"><div><div class="text-h4 page-title">Ventas de mostrador</div><div class="page-subtitle">Ventas directas con descuento automático de stock disponible.</div></div><q-btn class="action-primary" icon="point_of_sale" label="Nueva venta" @click="openNew" /></div>
    <q-card flat class="panel">
      <q-card-section class="row q-col-gutter-sm"><div class="col-12 col-md-8"><q-input v-model="search" outlined dense dark clearable label="Buscar por número, cliente o estado"><template #prepend><q-icon name="search" /></template></q-input></div><div class="col-12 col-md-4 text-right"><q-btn flat color="cyan-4" icon="refresh" label="Actualizar" :loading="loading" @click="load" /></div></q-card-section>
      <q-table :rows="filtered" :columns="columns" row-key="id" dark flat class="table-dark" :loading="loading">
        <template #body-cell-cliente="p"><q-td :props="p">{{ p.row.usuario?.Nombre ? `${p.row.usuario.Nombre} ${p.row.usuario.Apellido||''}` : p.row.cliente || `Cliente #${p.row.id_usuario}` }}</q-td></template>
        <template #body-cell-Total="p"><q-td :props="p" class="text-green-3 text-weight-bold">Bs {{ money(p.row.Total) }}</q-td></template>
        <template #body-cell-Estado="p"><q-td :props="p"><q-chip dense :color="p.row.Estado==='Entregado'?'green-10':p.row.Estado==='Cancelado'?'red-10':'amber-10'" text-color="white">{{ p.row.Estado }}</q-chip></q-td></template>
        <template #body-cell-acciones="p"><q-td :props="p"><q-btn flat round dense color="cyan-4" icon="picture_as_pdf" @click="pdf(p.row)" /><q-btn flat round dense color="amber-4" icon="edit" @click="editStatus(p.row)" /></q-td></template>
      </q-table>
    </q-card>

    <q-dialog v-model="dialog" persistent><q-card class="panel text-white" style="width:900px;max-width:96vw"><q-card-section class="row items-center justify-between"><div><div class="text-h6 text-weight-bold">Nueva venta</div><div class="text-caption text-muted">Solo se puede vender stock disponible.</div></div><q-btn flat round icon="close" v-close-popup /></q-card-section><q-separator dark/><q-card-section>
      <div class="row q-col-gutter-md"><div class="col-12 col-md-6"><q-select v-model="form.id_usuario" :options="clients" option-value="id" :option-label="clientLabel" emit-value map-options outlined dense dark label="Cliente *" /></div><div class="col-6 col-md-3"><q-input v-model="form.Fecha" type="date" stack-label outlined dense dark label="Fecha" /></div><div class="col-6 col-md-3"><q-select v-model="form.Estado" :options="['Pendiente','Entregado']" outlined dense dark label="Estado" /></div></div>
      <q-separator dark class="q-my-md"/><div class="row items-center justify-between q-mb-sm"><div class="text-subtitle1 text-weight-bold">Detalle de productos</div><q-btn outline color="cyan-4" icon="add" label="Agregar" @click="addItem" /></div>
      <div v-for="(item,idx) in form.items" :key="idx" class="row q-col-gutter-sm items-center q-mb-sm"><div class="col-12 col-md-6"><q-select v-model="item.id_producto" :options="products" option-value="id" option-label="Nombre" emit-value map-options outlined dense dark label="Producto *" @update:model-value="syncPrice(item)" /></div><div class="col-4 col-md-2"><q-input v-model.number="item.cantidad" type="number" min="1" outlined dense dark label="Cantidad" /></div><div class="col-5 col-md-2"><q-input :model-value="money(item.precio_unitario)" readonly outlined dense dark label="Precio" prefix="Bs" /></div><div class="col-3 col-md-2 row justify-end items-center"><span class="text-green-3 q-mr-sm">{{ money(item.cantidad*item.precio_unitario) }}</span><q-btn flat round dense color="red-4" icon="delete" @click="removeItem(idx)" /></div></div>
      <div class="text-right text-h6 q-mt-md">Total: <span class="text-green-3">Bs {{ money(total) }}</span></div>
    </q-card-section><q-card-actions align="right" class="q-pa-md"><q-btn flat label="Cancelar" v-close-popup/><q-btn class="action-primary" label="Registrar venta" :loading="saving" @click="save"/></q-card-actions></q-card></q-dialog>

    <q-dialog v-model="statusDialog"><q-card class="panel text-white" style="width:420px;max-width:92vw"><q-card-section class="text-h6">Actualizar venta #{{ selected?.id }}</q-card-section><q-card-section><q-select v-model="status" :options="['Pendiente','Entregado','Cancelado']" outlined dark label="Estado" /></q-card-section><q-card-actions align="right"><q-btn flat label="Cancelar" v-close-popup/><q-btn class="action-primary" label="Guardar" @click="saveStatus"/></q-card-actions></q-card></q-dialog>
  </q-page>
</template>
<script setup>
import { computed,onMounted,ref } from 'vue'; import { useQuasar } from 'quasar'; import api from '../services/api'; import { downloadPdf } from '../utils/download'
const $q=useQuasar(); const rows=ref([]),products=ref([]),clients=ref([]),loading=ref(false),saving=ref(false),dialog=ref(false),statusDialog=ref(false),selected=ref(null),status=ref('Pendiente'),search=ref('')
const columns=[{name:'id',label:'#',field:'id',align:'left'},{name:'Fecha',label:'Fecha',field:'Fecha',align:'left'},{name:'cliente',label:'Cliente',field:'cliente',align:'left'},{name:'Estado',label:'Estado',field:'Estado',align:'center'},{name:'Total',label:'Total',field:'Total',align:'right'},{name:'acciones',label:'Acciones',field:'acciones',align:'center'}]
const today=()=>new Date().toISOString().slice(0,10); const newForm=()=>({id_usuario:null,Fecha:today(),Estado:'Entregado',items:[{id_producto:null,cantidad:1,precio_unitario:0}]}); const form=ref(newForm()); const money=v=>Number(v||0).toFixed(2); const clientLabel=c=>`${c.Nombre||''} ${c.Apellido||''}`.trim()||`Cliente #${c.id}`
const total=computed(()=>form.value.items.reduce((s,i)=>s+Number(i.cantidad||0)*Number(i.precio_unitario||0),0)); const filtered=computed(()=>{const q=search.value.toLowerCase().trim();return !q?rows.value:rows.value.filter(r=>`${r.id} ${r.Estado||''} ${r.usuario?.Nombre||''} ${r.usuario?.Apellido||''}`.toLowerCase().includes(q))})
const load=async()=>{loading.value=true;try{const [a,b,c]=await Promise.all([api.get('/pedidos?canal=Mostrador'),api.get('/productos'),api.get('/usuarios')]);rows.value=a.data.pedidos||a.data.data||a.data||[];products.value=b.data.productos||[];clients.value=c.data.usuarios||c.data.data||c.data||[]}catch(e){$q.notify({type:'negative',message:e.userMessage||'No se pudo cargar ventas'})}finally{loading.value=false}}
const openNew=()=>{form.value=newForm();dialog.value=true}; const addItem=()=>form.value.items.push({id_producto:null,cantidad:1,precio_unitario:0}); const removeItem=i=>{if(form.value.items.length>1)form.value.items.splice(i,1)}; const syncPrice=item=>{const p=products.value.find(x=>x.id===item.id_producto);item.precio_unitario=Number(p?.Precio||0)}
const save=async()=>{for(const i of form.value.items){const p=products.value.find(x=>x.id===i.id_producto);if(!p||Number(i.cantidad)<1)return $q.notify({type:'warning',message:'Completa todos los productos.'});if(Number(i.cantidad)>Number(p.Disponible ?? p.Stock))return $q.notify({type:'warning',message:`Stock insuficiente para ${p.Nombre}. Disponible: ${p.Disponible ?? p.Stock}`})}if(!form.value.id_usuario)return $q.notify({type:'warning',message:'Selecciona un cliente.'});saving.value=true;try{await api.post('/pedidos',form.value);dialog.value=false;$q.notify({type:'positive',message:'Venta registrada y stock descontado.'});await load()}catch(e){$q.notify({type:'negative',message:e.userMessage||'No se pudo registrar la venta'})}finally{saving.value=false}}
const pdf=async r=>{try{await downloadPdf(`/pedidos/${r.id}/pdf`,`venta-${r.id}.pdf`)}catch{$q.notify({type:'negative',message:'No se pudo generar el PDF.'})}}; const editStatus=r=>{selected.value=r;status.value=r.Estado;statusDialog.value=true}; const saveStatus=async()=>{try{await api.put(`/pedidos/${selected.value.id}`,{Estado:status.value});statusDialog.value=false;await load()}catch(e){$q.notify({type:'negative',message:e.userMessage||'No se pudo actualizar'})}}
onMounted(load)
</script>
